steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'functions'
  - 'deploy'
  - 'telegram_webhook'  # function name
  - '--runtime'
  - 'python310'
  - '--trigger-http'
  - '--allow-unauthenticated' 